app/user/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from app.models import User


class BookmarkForm(FlaskForm):
	href = StringField('href', validators=[DataRequired()])
	submit = SubmitField('Submit')

app/user/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views, errors
from ..models import Permission

@user.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/user/views.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.urls import url_parse
from urlparse import urlparse
from datetime import datetime

from app import app, db
from . import user
from .forms import BookmarkForm
from ..models import User, Bookmark, Permission
from ..util import url_resolve

@user.route('/')
@login_required
def index():
	return render_template('user/index.html', title = '在读', table='queue')

@user.route('/archive')
@login_required
def archive():
	return render_template('user/index.html', title = '已读', table='archive')
	
@user.route('/favorite')
@login_required
def favorite():
	return render_template('user/index.html', title = '精华', table = 'favorite')
	
@user.route('/tags')
@login_required
def tags():
	return render_template('user/index.html', title = '标签', table='tags')

app/templates/user/edit.html
{% extends "base.html" %}

{% block content %}
	<form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br>
            {{ form.title(size=32) }}<br>
            {% for error in form.title.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.href.label }}<br>
            {{ form.href(size=64) }}<br>
            {% for error in form.href.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
	
{% endblock %}

app/templates/user/index.html
{% extends "base.html" %}

{% block content %}
	<div class="subnav">
		<div class="btn-group " role="group" aria-label="...">
		  <div class="btn-group" role="group">
			<a type="button" {% if table=='queue' %} class="btn btn-primary" {% else %} class="btn btn-default" {% endif %} href="{{ url_for('user.index') }}">在读</a>
		  </div>
		  <div class="btn-group" role="group">
			<a type="button" {% if table=='archive' %} class="btn btn-primary" {% else %} class="btn btn-default" {% endif %} href="{{ url_for('user.archive') }}">已读</a>
		  </div>
		  <div class="btn-group" role="group">
			<a type="button" {% if table=='favorite' %} class="btn btn-primary" {% else %} class="btn btn-default" {% endif %} href="{{ url_for('user.favorite') }}">精华</a>
		  </div>
		  <div class="btn-group" role="group">
			<a type="button" {% if table=='tags' %} class="btn btn-primary" {% else %} class="btn btn-default" {% endif %} href="{{ url_for('user.tags') }}">标签</a>
		  </div>
		</div>
	</div>

	<div class="page_queue_list">
	</div>

	<div class="loading">
		<div class="btn-group btn-group-justified" role="group" aria-label="...">
		  <div class="btn-group" role="group">
			<button type="button" class="btn btn-default" id="btn-loading">加载更多...</button>
		  </div>
		</div>
	</div>
{% endblock %}

{% block extra_js %}
<script src="{{ url_for('static', filename='js/item.js') }}"></script>
<script>
itemLoadPara('{{table}}', '');
itemLoadMore();
</script>
{% endblock %}

app/templates/user/sedit.html
<div class="modal-dialog">
    <div class="modal-content">
        <form id="editForm" action="{{formaction}}" class="customized-form" role="form" method="post">
			{{ form.hidden_tag() }}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">编辑书签</h4>
            </div>
            <div class="modal-body">

                <div class="form-group">
					<label for="bm_href" class="control-label"> 地址 </label>
					<input type="text" class="form-control" id="href" name="href" required value="{{form.href.data}}">
				</div>
                <div class="form-group">
					<label for="bm_title" class="control-label"> 标题 </label>
					<input type="text" class="form-control" id="title" name="title" required value="{{form.title.data}}">
				</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" value="no" data-dismiss="modal">取消</button>
                <button type="submit" class="btn btn-primary" value="ok" id="submitEditBtn">修改</button>
            </div>
        </form>
    </div><!-- /.modal-content -->
</div><!-- /.modal -->

<script type="text/javascript">           
$(document).ready(function() { 
	var options = { 
		beforeSubmit:  showRequest,  // 提交前
		success:       showResponse,  // 提交后 
		//另外的一些属性: 
		//url:       url         // 默认是form的action，如果写的话，会覆盖from的action. 
		//type:      type        // 默认是form的method，如果写的话，会覆盖from的method.('get' or 'post').
		//dataType:  null        // 'xml', 'script', or 'json' (接受服务端返回的类型.) 
		//clearForm: true        // 成功提交后，清除所有的表单元素的值.
		resetForm: true        // 成功提交后，重置所有的表单元素的值.
		//由于某种原因,提交陷入无限等待之中,timeout参数就是用来限制请求的时间,
		//当请求大于3秒后，跳出请求. 
		//timeout:   3000 
	}; 
	
	// 提交前
	function showRequest(formData, jqForm, options) { 
	 // formdata是数组对象,在这里，我们使用$.param()方法把他转化为字符串.
	  var queryString = $.param(formData); //组装数据，插件会自动提交数据
	  //alert(queryString); //类似 ： name=1&add=2  
	  return true; 
	} 

	  //  提交后
	function showResponse(responseText, statusText)  { 
		   //alert('状态: ' + statusText + '\n 返回的内容是: \n' + responseText);
		   window.location.reload();
	 } 
 
	//'ajaxForm' 方式的表单 .
	$('#editForm').ajaxForm(options);
}); 
</script>

app/templates/user/user.html
{% extends "base.html" %}
{% import "_pages.html" as page %}

{% block content %}
    <h1>User: {{ user.username }}</h1>
    <hr>
	{% if bookmarks%}
	<table class="table table-bordered">
	<thead>
	  <tr>
		<th>标题</th>
		<th>发布时间</th>
		{% if current_user == user or current_user.is_administrator() %}
		<th>管理</th>
		{% endif %}
		</tr>
	</thead>
	<tbody>
	{% for bookmark in bookmarks %}
	<tr class="active">
		<td><a href="{{bookmark.href}}">{{ bookmark.title }}</a></td>
		<td>{{ moment(bookmark.time_updated).format('YYYY-MM-DD HH:mm') }}</td>
		{% if current_user == user or current_user.is_administrator() %}
		<td>
			<button type="button" class="bmedit btn btn-default btn-xs" data-src="{{bookmark.id}}" onclick="showEditModal({{bookmark.id}})">编辑</button>
			<a class="btn btn-default btn-xs" href="{{ url_for('admin.delete_bookmark',id=bookmark.id) }}">删除</a>
		</td>
		{% endif %}
	</tr>
	{% endfor %}
	</tbody>
	</table>

	<div class="pagination">
	{{ page.pages(pagination, 'user.users', username=user.username) }}
	</div>
	{% endif %}
{% endblock %}

app/templates/user/write.html
{% extends "base.html" %}

{% block content %}
	<form action="" method="post">
        {{ form.hidden_tag() }}
		<div class="form-group">
            <label for="bm_href"> 地址 </label>
            <input type="text" class="form-control" id="href" name="href" required placeholder="Url">
            {% for error in form.href.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
		</div>
		<button type="submit" class="btn btn-default">发布</button>
    </form>
{% endblock %}